version: '3.7'
services:
  phpunit:
    #build: ./php7-testing-phpunit
    build:
      context: ./php7-testing-phpunit
      dockerfile: Dockerfile
    image: dominikstyp/phpunit_php7
    volumes:
      - ./tests:/app/tests:cached
      - ./vendor:/tmp/vendor_mapped:cached